version: '2'
services:
  db:
    image: postgres:9.4
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
      
  node:
    build: ../application/.
    container_name: ${COMPOSE_PROJECT_NAME}_web
    working_dir: /app
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:app.${PROJECT_BASE_URL}'
    expose:
      - "3000"
    links:
      - "db"

  traefik:
    image: traefik
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
